version: '3'
services:
    mongo_wolf:
        container_name: mongo_wolf
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: wolf
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: wolf
        volumes:
            - ./mongo-init/:/docker-entrypoint-initdb.d/
        ports:
            - 27017:27017

    api:
        container_name: api_wolf
        build: ./../api
        links:
          - mongo_wolf
        ports:
            - 3000:3000
        env_file:
            ./api.env
        environment:
          - NODE_ENV=production
    
    # client:
    #     container_name: angular_wolf
    #     build: ./../client
    #     volumes:
    #         - ./../client:/usr/src/app
    #     ports: 
    #         - 4200:4200
    #     command: >
    #         bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"